name: Phoenix Test Automation Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      env:
        description: "Envoirnment"
        type : choice
        options : [qa,uat,dev]
        required: true
        default : qa
        
    

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Execute test automation framework
      run: mvn test -DsuiteXmlFile=testNg.xml -Denv="${{ github.event.inputs.env }}"
    - name: Upload a Build Artifact
      uses : actions/upload-artifact@v4.6.2
      with : 
        name: SureFire Report
        path: target/surefire-reports/
        retention-days: 10
     
